{
    "name": "Home Service Tres Joliee",
    "version": "1.0",
    "author": "Al Kidhma Group",
    "website": "",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "summary": "Home Service",
    "description": """ """,
    "depends": ['beauty_soft', 'beauty_pos', 'point_of_sale'],
    "data": [
        "views/pos_category.xml",
        "views/pos_order.xml",
        "views/res_partner_view.xml",
    ],
    "demo": [],
    "test": [],
    "images": [],
    'qweb': [],
    "css": [],
    "sequence": 1,
    "application": True,
    "installable": True,
    "auto_install": False,
}
