{
    "name": "Free of Cost report",
    "version": "1.0",
    "author": "Al Kidhma Group",
    "website": "",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "summary": "FOC Report",
    "description": """ """,
    "depends": ['beauty_foc'],
    "data": [
        "views/foc_wizard.xml",
    ],
    "demo": [],
    "test": [],
    "images": [],
    'qweb': [],
    "css": [],
    "sequence": 1,
    "application": True,
    "installable": True,
    "auto_install": False,
}
