{
    "name": "A4 Receipt print Tres Joliee",
    "version": "1.0",
    "author": "Al Kidhma Group",
    "website": "",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "summary": "A4 Receipt print",
    "description": """ """,
    "depends": ['beauty_soft', 'beauty_pos', 'combo_packs_management'],
    "data": [
        "views/combo.xml",
        "views/combo_pack.xml",
        "views/pos_order.xml",
        "views/res_partner_view.xml",
        "reports/report_pos_invoice.xml",
    ],
    "demo": [],
    "test": [],
    "images": [],
    'qweb': [],
    "css": [],
    "sequence": 1,
    "application": True,
    "installable": True,
    "auto_install": False,
}
