{
    'name': 'Card Charges Management',
    'version': '1.0',
    'category': 'Accounting &amp; Finance',
    'sequence': 6,
    'author': 'Al Kidhma Group',
    'company': 'Al Kidhma Group',
    'website': 'http://www.alkidhmagroup.com',
    'summary': '',
    'depends': ['account', 'account_accountant','mail', 'report', 'account_cancel'],
    'data': [
        'data/data.xml',
        'security/ir.model.access.csv',
        'security/multi_company_security.xml',
        'views/res_config_settings_views.xml',
        'views/res_company.xml',
        'views/card_charges.xml',
        'views/account_move.xml',
        'wizard/card_report_wizard.xml',
        'report/card_report_template.xml',
        'report/report.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': '_create_journal_and_accounts',
}
