{
    "name": "Appointment States",
    "version": "1.0",
    "author": "Al Kidhma Group",
    "website": "",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "summary": "Appointment States",
    "description": """ """,
    "depends": ['beauty_pos', 'sms_management'],
    "data": [
        "wizard/appointment_book_wizard.xml",
        "views/pos_order.xml",
        "views/sms_template.xml",
        "reports/appointment_report_template.xml",
    ],
    "demo": [],
    "test": [],
    "images": [],
    'qweb': [],
    "css": [],
    "sequence": 1,
    "application": True,
    "installable": True,
    "auto_install": False,
}
